#!/bin/bash

output=$(eval git show -U0 | ./diff-lines2)
echo "$output"

if [[ -z "$output" ]]; then
    echo "No diff in this version, Not applying any breakpoints"
    exit 0
fi

repoUrl=$(git remote get-url origin)

echo "$output" | while IFS= read -r line; do
    filename=$(echo "$line" | awk -F' ' '{print $1}')
    lineno=$(echo "$line" | awk -F' ' '{print $2}')

 curl --location 'https://staging.rookout.com/api/v2/breakpoints/create' \
  --header 'X-Api-Key: '"$ROOKOUT_API_KEY" \
  --header 'Content-Type: application/json' \
  --data-raw '{
  "userEmail": "nathan@rookout.com",
  "filepath": "'"$filename"'",
  "lineNumber": '"$lineno"',
  "repositoryURL": "'"$repoUrl"'",
  "repositoryRevision": "master"
  }'
done