#!/bin/bash

output=$(eval git show -U0 | ./diff-lines | awk -F:  'match($1,/py/){ print $1 " " $2 }' | uniq)
#echo "$output"


./rookctl auth-pass $ROOKOUT_USERNAME $ROOKOUT_PASSWORD
./rookctl org use "demo"
./rookctl filter add "type:saas-nathan"
echo "$output" | while IFS= read -r line ; do ./rookctl bp set -o rookout -n tutorial-python $line ; done
