#! /bin/bash


diff-lines() {
    local path=
    local line=
    local content=
    while read; do
        esc=$'\033'
        if [[ $REPLY =~ ---\ (a/)?.* ]]; then
            continue
        elif [[ $REPLY =~ \+\+\+\ (b/)?([^[:blank:]$esc]+).* ]]; then
            path=${BASH_REMATCH[2]}
        elif [[ $REPLY =~ @@\ -[0-9]+(,[0-9]+)?\ \+([0-9]+)(,[0-9]+)?\ @@.* ]]; then
            line=${BASH_REMATCH[2]}
        elif [[ $REPLY =~ ^($esc\[[0-9;]*m)*([\ +-])(.*) ]]; then
            content=${BASH_REMATCH[3]}
#            echo $content
            if [[ -n $content && $content != *"import"* && $content != *"def "* ]]; then
                echo "$path:$line:$REPLY"
            fi
            if [[ ${BASH_REMATCH[2]} != - ]]; then
                ((line++))
            fi
        fi
    done
}

diff-lines | awk -F:  'match($1,/py/){ print $1 " " $2 }' | uniq